// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoXl20ReA7g2SbBZtBIfo9Xa448oXMMFQ',
    appId: '1:930079766574:web:76709aad47a9226d1187bf',
    messagingSenderId: '930079766574',
    projectId: 'authorize-mq-app',
    authDomain: 'authorize-mq-app.firebaseapp.com',
    storageBucket: 'authorize-mq-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWNBXJQYQ8p-Zi6nmisgWMvdcuclV_ljA',
    appId: '1:930079766574:android:4d9201a85b06d32d1187bf',
    messagingSenderId: '930079766574',
    projectId: 'authorize-mq-app',
    storageBucket: 'authorize-mq-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClcZjhlKgpoAa4JQogS7gW5dHxXSt7sj4',
    appId: '1:930079766574:ios:87688a1c0e99ec3a1187bf',
    messagingSenderId: '930079766574',
    projectId: 'authorize-mq-app',
    storageBucket: 'authorize-mq-app.appspot.com',
    iosBundleId: 'com.example.macquarieApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClcZjhlKgpoAa4JQogS7gW5dHxXSt7sj4',
    appId: '1:930079766574:ios:f5a5069409e0525e1187bf',
    messagingSenderId: '930079766574',
    projectId: 'authorize-mq-app',
    storageBucket: 'authorize-mq-app.appspot.com',
    iosBundleId: 'com.example.macquarieApplication.RunnerTests',
  );
}
